{% set name = "jsonapi-client" %}
{% set version = "0.9.6" %}
{% set sha256 = "4325240a8357147e410f3600ae224edbefeaaebed1e70bdf8776d4b5d7a3377d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/qvantel/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [py < 36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - jsonschema
    - aiohttp

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-mock
  commands:
    - py.test tests

about:
  home: https://github.com/qvantel/jsonapi-client
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Comprehensive, yet easy-to-use, pythonic, ORM-like access to JSON API services'

  dev_url: https://github.com/qvantel/jsonapi-client

extra:
  recipe-maintainers:
    - sodre
