{% set name = "jsonapi-client" %}
{% set version = "0.9.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsonapi_client-{{ version }}.tar.gz
  sha256: 348bb9efb5f98421f865f8258dae5aa781552a5910351ff578f084292e659cd1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp
    - jsonschema
    - python >=3.6
    - requests

test:
  imports:
    - jsonapi_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qvantel/jsonapi-client
  summary: Comprehensive, yet easy-to-use, pythonic, ORM-like access to JSON API services
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sodre
    - emilhaegglund
