travis:
  secure:
    BINSTAR_TOKEN: tGBxqqeaKHBV6hvtxBrViHwQOgC1/MyWeD85veUm3Cwb1udTn94XYXfJJ7ICPk+CfYLT8d3dYuB4x4TOrkYEumim+AlGbYQAiODo6Ic6pTJRAuDfL7TQoI6vJJszGmPgUHp9jsCVt136cFknC1l5kLgxGctK164WVS+R6IvHorIL1YaAaY30a9sxJSd2xG8fV1hG7rnH50/e7O1/W76OxqVi+qcZDy2sL42RUJLh24vGdbTwFY6FkOBV5JJ+mfegoelrElYCCX+KBUXQIW0MdZqu3+uTWxOpR6hdTmdq+aHHvuYehQo2qI1SIK3b4KL4IzrNoWiF/rlqSPUEaKE/RpPXyEW6PX+q1RxNWXtr3FBV1spgBKDTKfh+zL0hpuLF883n9uRn1CSE/i6C5ZALFmor3EVmeoWJPcmKM8osOb2kg3Nu6g2NHuQ1DEXY9ixIRRLQIZ8gPOlTMXmBIhoOfSd0Wwxwz3A+8wxbrEkg3krDC5fEh2CXdo6756mMCMmj1IJTsvlClR1+bGPQMjWQ+TyIoc7EE0LH/3uEc1t9xp01wx+fPL6PM801a4NyqikJADCeDUkAWdyVqm45m+npQ0gFMIPhtWR2j9e6+QCcEst5RYAGRcDG/zzbpaSBTr3KhF09GmS6rNwdkC9SfF2vx5AZaBDWb86OwgVi+gOG1Lc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
