travis:
  secure:
    BINSTAR_TOKEN: yqYMY8Qx3jyVYSMTHoivqpDgeQimR/j+m4l3rw3Xm6GBi/2MS457SRX0ZhAFT5NprkfFD+Y/10UlY7wh/ByC+AX21giuyw/C86u4TP5UjQL2SdVQzQ2L7Ogc2X3reHXy4IwUOf8u71mgCAy4yhThl4OoCSB+HOtzyZ7sgHJI9x4YBTnl47D7kZmpZU+n4/OXx6CldIfkoaAL4k/hY3MeIsXz/cDvIaI8N6LZJA+RSIZy1ZcfEP099joKpOmqfDiGYvtvfksG0zgrxYk7GUUVggyTVtFKvHnAyRVorsvz3wAxqcrExVzy1X5RuBEkybBxvenW5vESXrOQO/GALyiU1Vr8CvtHrmrL6dwV0SoEIjPGZQKaC9+K5XB8QPfq/BTYNElDWlD8epGqORaC/+JcE9GacoVNcTb+5ZTJIjPE3Mh+AKVOoIcr1b4gY0zHGoNjYfaajS5N3dwnZN2HOM8pzrVw2RbYvJQluB03JIA945rfwA2DfoAw2LsrV3I6WWLW2ZW2+CXXpaKQb9ZU4SMeFPdxzOYUTjI55ybPPAr3Z0LwpwBvSFV5Bkgeyb5FDK6nvYO8MFNJ644NFqFwcfa1MII1Vk09FqNceJY+X5BQKQmAI5q7meoGqeLSXhk5NRmajE3HNfmuczQruoB0L4iwJK3fgeVSk7kbSXYttntemJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
